module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      'persons',
      [
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test00',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test01',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test02',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test03',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test04',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test05',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test06',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test07',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test08',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test09',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test10',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test11',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test12',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test13',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test14',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test15',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test16',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test17',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test18',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test19',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test20',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test21',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test22',
          phone: '13312345678',
          state_id: '1',
          type_id: '1',
        },
        {
          created_at: new Date(),
          updated_at: new Date(),
          name: 'test23',
          phone: '13312345678',
          state_id: '1',
          type_id: '2',
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete('persons', null, {});
  },
};
